### ISSUE TITLE
add time filters to collection and source details page

### ISSUE THREAD

**Issue by rahulbot** [mitmedialab/MediaCloud-TopicMapper#345]
We need to start working on the features that will eventually support the new Dashboard.  One is the idea that we can query a specific collection or source on the detail page.  One way to bake this in now is to add support for switching the time period shown by the word cloud on the collection and source details pages.

This should look something like this:
<img width="621" alt="u_s__mainstream_media___media_cloud" src="https://cloud.githubusercontent.com/assets/673178/24073929/0daae466-0bd6-11e7-85e3-c1815f157896.png">
Those items in red are links that are dark grey be default, hover turns to `brandDarkColor` with an underline, and currently selected is `brandDarkColor`.  Default to "past week" (to improve page load time).

**Tasks:**
- [x] add optional `q` param support to server collection and source word count endpoints
- [x] add optional `q` param support to server collection and source word count CSV download endpoints
- [x] add optional `q` param support to `collectionWordCount` and `sourceWordCount` JS helpers
- [x] add support to save a `period` string (week, month, all) to both reducers
- [ ] add `COLLECTION_WORD_COUNT_PERIOD` and `SOURCE_WORD_COUNT_PERIOD` actions keys and action generators get fired with the appropriate period when a user clicks on one of these new links
- [x] have the `CollectionTopWordsContainer` generate the `q` param to send to server based on the `period` based in from state - ie. "week" turns into something like `(publish_date:[2017-03-11T00:00:00Z TO 2017-03-18T00:00:00Z])`
- [x] since we want this to act pretty similarly in two places, you can decide if you want to add this support to a new `PeriodicEditableWordCloudDataCard` or something, which would take a `onPerodChange` callback, render the links and a `EditableWordCloudDataCard` as children

**Comment by cindyloo** [comment]
if the query is not provided, what is the desired UI? do we have a default time period or do we not show it alll?

**Comment by rahulbot** [comment]
Great question! All "all time" to this list of options shown and make it default. Does that sound reasonable?

**Comment by cindyloo** [comment]
in the api.py wordCount, there is a parameter
`'q': solr_query,`
is the new query string denoting the time period part of this solr_query or entirely separate?

**Comment by rahulbot** [comment]
The time period should be sent over as the `q` param, NOT in a separate param.

**Comment by cindyloo** [comment]
I don't understand how I'm passing the time period information to the api client
re:
`def wordCount(self, solr_query, solr_filter='', languages='en', num_words=500, sample_size=1000, include_stopwords=False, include_stats=False):
        params = {
            'q': solr_query,
            'l': languages,
            'num_words': num_words,
            'sample_size': sample_size,
            'include_stopwords': 1 if include_stopwords is True else 0,
            'include_stats': 1 if include_stats is True else 0,
        }
        if len(solr_filter) > 0:
            params['fq'] = solr_filter
        return self._queryForJson(self.V2_API_URL+'wc/list', params)`

**Comment by cindyloo** [comment]
to be more clear, only the parameter` 'media_id:'+str(media_id))` is passed in as the query parameter to wordCount. What is the precise name of this new time period that the backend will understand? is it "publish_date"?

**Comment by rahulbot** [comment]
Yes. As noted above, the JS component needs to add a date string like this: '(publish_date:[2017-03-11T00:00:00Z TO 2017-03-18T00:00:00Z])'. So the q param will be something like '(media_id: 1124) and (publish_date:[2017-03-11T00:00:00Z TO 2017-03-18T00:00:00Z])'. Regular SOLR query syntax. You should probably put the date generation for lastWeek and such in dateUtil.js because Im sure we'll want to use it in other places.

**Comment by cindyloo** [comment]
hm, not sure if my syntax is correct here but this is what I have:
url:
`http://localhost:5000/#/sources/1094?q='(publish_date':[2017-10-11T00:00:00Z TO 2017-03-18T00:00:00Z])'`
and I get an undefined field response:
`Error fetching Solr response: Solr error: \"undefined field: \"publish_date'\"\", params: {\"df\":\"sentence\",\"fl\":\"story_sentences_id\",\"q\":\"( media_id:1094 AND '(publish_date':[2017-10-11T00:00:00Z TO 2017-03-18T00:00:00Z])' ) AND ( * )\",\"rows\":\"5000\",\"sort\":\"random_1 asc\",\"wt\":\"json\"} at lib/Med`

maybe use start_date?

**Comment by cindyloo** [comment]
ok, misplaced quotes. now working:
example url: `http://localhost:5000/#/sources/1094?q='(publish_date:[2017-12-11T00:00:00Z TO 2017-03-18T00:00:00Z])'`
response:
`query GET to https://api.mediacloud.org/api/v2/wc/list with {'fq': u"media_id:1094 AND '(publish_date:[2017-12-11T00:00:00Z TO 2017-03-18T00:00:00Z])'", 'l': None, 'q': '*', 'sample_size'`

**Comment by cindyloo** [comment]
are we supporting a bookmark for this? (if so hard to infer UI display unless we stipulate the kind of timeperiod FYI)

**Comment by cindyloo** [comment]
I'd think we want the `EditableWordCloudDataCard` to make the call to dateUtil for the query string creation (source url passed in from the `topWordsContainer`) when the user clicks on one of its four links within that datacard. The query is added to the URL and detecting a change, the container fetches the data again... 
we could just as easily pass in a callback from the `topWordsContainer`, but it seems the behavior belongs in the datacard

**Comment by cindyloo** [comment]
we don't really need new Actions, do we? I am just adding the query as a param so we can piggy-back on the regular fetchTopWords action

**Comment by cindyloo** [comment]
and afaik, we dont' need the update to the reducer as it simply returns the new list of words per query params

**Comment by rahulbot** [comment]
Correct on both. Use the existing action, and no reducer updates needed.

**Comment by cindyloo** [comment]
are these links supposed to be red and raised? (vs blue or brand color?)

**Comment by rahulbot** [comment]
Colors are described above just under the screenshot mockup:
"Those items in red are links that are dark grey by default, hover turns to brandDarkColor with an underline, and currently selected is brandDarkColor. Default to "past week" (to improve page load time)."

**Comment by cindyloo** [comment]
ah scanned right past that. Will update. fyi, we decided to defaulting to all, (not past week as originally noted).

**Comment by cindyloo** [comment]
hmm... I guess if we want to have the timePeriod link reflect what was just clicked, we do in fact have to push it through the reducer, right? The TopWordsContainer re-renders, and we lose any local state level variable we may have set in the clickHandler (eg this.setState({ timePeriod })

**Comment by cindyloo** [comment]
notes: neigther moment().format('YYYY-MM-DDThh:mm:ssZ'); nor SOLR_FORMAT: 'YYYY-MM-DDTHH:mm:ssZ' was considered valid by SOLR.  I had to add the "Z" external to the formatting function.
the UI extends across the page- it looks like a merge from master w/r/to Word Tree did this.. we will need to do more tomorrow...

**Comment by cindyloo** [comment]
selection/defaulting of link choice almost done. But, the whole datacard disappears then reappears when fetching again, not sure that we want that...

**Comment by cindyloo** [comment]
created pull request, but check the above notes before merging....

**Comment by cindyloo** [comment]
need collections UI!
